### ISSUE TITLE
RPPD extraction (alpha LVS)

### ISSUE THREAD

**Issue by bmurmann** [IHP-GmbH/IHP-Open-PDK#100]
A series combination of RPPD (as shown below) matches the schematic only with option --no_simplify. But this option won't work for many other parts of a real circuit. Any remedies that can be implemented?

My test cases has 26 resistors in series in the layout and 26 resistors in series in the schematic. When any simplifications are turned on, there is no more match, since the derived simplifications between sch and lay differ.

This could be a general KLayout issue?

![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/62622760/2af8068f-7a8d-427a-b75f-29abc7af3d1a)

**Comment by sergeiandreyev** [comment]
Hello @bmurmann, could you please confirm that with the latest LVS update the issue is fixed?

**Comment by bmurmann** [comment]
Confirmed, this is fixed.
