### ISSUE TITLE
Overlapping vias in IO cell

### ISSUE THREAD

**Issue by dnltz** [IHP-GmbH/IHP-Open-PDK#115]
See https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1677

This issue is still present in the most recent and had to be fixed manually for the second time.

**Comment by dnltz** [comment]
@stafverhaegen-chipflow I opend an issue because this is still not fixed. If this only requires to change the cell in klayout, I could also do it. I would need some help/assistance.

**Comment by Fatsie** [comment]
I was not aware as I thought previous tape-out could go without needing further fix.
This needs fix in LEF. I'll see how to do it in the coming days.

**Comment by dnltz** [comment]
@Fatsie sorry, we have another bug in my current design but it's unrelated to this and IO cells in general.
