### ISSUE TITLE
DRC violation in sealring

### ISSUE THREAD

**Issue by dnltz** [IHP-GmbH/IHP-Open-PDK#116]
Layout rules define GFil.d with a gap of 1.1u between GatPoly:filler and pSD. The current  sealring only has 1.0u and therefore fails this check.

![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/37450464/3bfecf93-2f5a-4cc3-9f5e-60b7576a58b0)

**Comment by dnltz** [comment]
Only the horizontal filler cells are affected. Verticals have a gap of 1.1u.

**Comment by dnltz** [comment]
https://github.com/IHP-GmbH/IHP-Open-PDK/blob/f5c16b18d8d7048e65e7bd63d392d065fec73d4b/ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/sealring_code.py#L191

**Comment by sergeiandreyev** [comment]
Unfortunately, after review we see that we have a disconnect between the `sealring` in the OpenPDK and the internal one:
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/116548619/903deafe-f716-4c18-99d4-a234d41e767b)
we're going to remove the internal filler generation code altogether from the `sealring` Pycell, this way the external script should be used and also we will get rid of these errors that you're mentioning here

**Comment by dnltz** [comment]
Should be solved with https://github.com/IHP-GmbH/IHP-Open-PDK/pull/117

@sergeiandreyev can we close it?

**Comment by sergeiandreyev** [comment]
yes, sure, thank you again!
in the meantime I'll cross check the updated Pycell with the internal implementation
