### ISSUE TITLE
wirebond-pads and ESD protection

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#12]
i would like to know how wirebond-pads and ESD-protection should be done in iHPs and skywaters 130nm BiCMOS processes. is there some documentation? i didnt found anything in the PDKs

**Comment by olisnr** [comment]
when i open the **sg13g2_pr.gds** from the PDK, i see many interessting cells. "bondpad" or "diodevdd_2kv" as example. buuuut there is no model for ngspice in the **IHP-Open-PDK-main/ihp-sg13g2/libs.tech/ngspice/models** and no documentation in the **SG13G2_os_process_spec.pdf**

HELP!

**Comment by sergeiandreyev** [comment]
This PDK is in early alpha state. This means the PDK is still in development and not comprehensive tested by IHP. The PDK may contain [serious] errors and may not contain all of the features that are planned for the final version. But we're working constantly on this project to offer as stable PDK as possible to the community.

**Comment by sergeiandreyev** [comment]
Regardibg the `bondpad` cell I can comment that we do not have a "real" model for it even in the commercial PDK, so please use just a 'placeholder' for this device.
