### ISSUE TITLE
Mention OpenROAD & in support tools

### ISSUE THREAD

**Issue by maliberty** [IHP-GmbH/IHP-Open-PDK#126]
Please add OpenROAD and OpenROAD-flow-scripts to your "Supported EDA Tools" section.

**Comment by KrzysztofHerman** [comment]
@maliberty thank you for pointing this out. Respective PR is awaiting approval.

**Comment by maliberty** [comment]
This does not seem to be fixed as I don't see it listed

**Comment by sergeiandreyev** [comment]
Hi @maliberty, 
 actually it's changed in the `dev` branch:
 https://github.com/IHP-GmbH/IHP-Open-PDK/tree/dev
But indeed we need to update the `main` one

**Comment by maliberty** [comment]
Ok, can you make the change or reopen this issue?  main is what people see by default.
