### ISSUE TITLE
how was the layout versus scheme verification done ...

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#130]
... for the standard logic cells? using commercial tools? or were the cells just tested against design rule violation?

i would like to know if there is an alternative LVS method until the LVS works.

**Comment by KrzysztofHerman** [comment]
@olisnr our STD cells were generated and verified (DRC, LVS) using proprietary tools, you can also run DRC (limited) and LVS using Klayout.

**Comment by olisnr** [comment]
thanks a lot
