### ISSUE TITLE
Does this have MEMRES model?

### ISSUE THREAD

**Issue by radhe-2022** [IHP-GmbH/IHP-Open-PDK#143]
On Europractice I found that IHP Technologies SG13S have MEMRES model. But I am unable to find this model..How can I get access to this?

https://europractice-ic.com/technologies/asics/ihp/

**Comment by KrzysztofHerman** [comment]
@radhe-2022 as you could see we provide many variants of SG13G2 technology however at this moment we do not provide support for memristors in the open source domain.

**Comment by sergeiandreyev** [comment]
Hi @radhe-2022, does it answer your question? Do you have any additional feedback?

**Comment by sergeiandreyev** [comment]
closing this issue as no response from the user
