### ISSUE TITLE
Resistor parameter `b` usage?

### ISSUE THREAD

**Issue by hpretl** [IHP-GmbH/IHP-Open-PDK#191]
The poly resistor has parameters `m` and `b`. `m` is likely multiplicity, e.g. how many resistors in parallel, but what is `b`?

<img width="241" alt="image" src="https://github.com/user-attachments/assets/87fd7461-b08c-4377-9466-39796dd70ea8">

**Comment by sergeiandreyev** [comment]
`b` is number of bends
![image](https://github.com/user-attachments/assets/fdb0e3d7-bb63-433f-acda-6456ee8c13c2)
here `b=2`

**Comment by hpretl** [comment]
Thanks! So no parameter for number of pieces in series (I am usually not using bends).

**Comment by sergeiandreyev** [comment]
no, maybe we could consider this as an enhancement, but we need to discuss this internally to be aligned with commercial PDK

**Comment by sergeiandreyev** [comment]
Hi @hpretl, after talking it over, we decided not to go ahead with series implementation

**Comment by hpretl** [comment]
OK, then let's close this.
