### ISSUE TITLE
a question to LVS from .spice

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#196]
while the LVS script, seem to analyse my `.gds`, it does nothing with the `.spice`. i tried also with the options `Netlist Only` and `Top Level Pins`.

can anybody get me a hint what could be wrong on the spice netlist? or is the script not ready to analyse .spice now?

[OTA_LVS.spice.tar.gz](https://github.com/user-attachments/files/16933924/OTA_LVS.spice.tar.gz)

**Comment by d-m-bailey** [comment]
@olisnr Before you create your spice netlist from xschem, set the `Simulation` -> `LVS netlist: top level is a .subckt` option.

**Comment by olisnr** [comment]
thanks a lot
