### ISSUE TITLE
.spice net for LVS

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#197]
it seems that the LVS script only looks for M-devices (spice MOSFETs). but if i understand it correct the spice-models are X-devices (sub-circuits (XM with the use-spice-prefix option in Xschem)).

should this be changed? or documented? 

the other thing is that the LVS seems not to accept spice parameters. will this be implemented? or
is it be possible to ignore optional {} values?

**Comment by sergeiandreyev** [comment]
so, while you can run the cross-check with the SPICE netlist as a schematic representation of the circuit, you'll have to do some preprocessing

**Comment by atorkmabrains** [comment]
@olisnr That might be because an issue in the design. It's how klayout is functioning.

**Comment by sergeiandreyev** [comment]
Hi @olisnr, could you please upload this testcase?

**Comment by olisnr** [comment]
@sergeiandreyev yes:
[ota_gds_netlist.zip](https://github.com/user-attachments/files/16985799/ota_gds_netlist.zip)

**Comment by sergeiandreyev** [comment]
I've made a quick review of the netlist, and checked the LVS on the testcase with commercial flow as well - the LVS is not clean (property, nets, instances, connectivity errors), but there are no top-level port related violations
I would expect however 'out <-> op' violation to show-up)
you have to follow the required syntax (f.e. device parameters are missing from the `.spice` file), also you have to check devices (cmim are missing from netlist)

**Comment by sergeiandreyev** [comment]
what I do not understand is why I have all netlist ports in Database browser in capital letters, while in the netlist file I have `ip in ip sink`:
![image](https://github.com/user-attachments/assets/36533859-011d-4e5d-b8c6-ea6f24125a82)
also, as you see, port names in layout are not consistent with your screenshot before

**Comment by olisnr** [comment]
@sergeiandreyev yes i used on older version of the `.gds` in the `.zip`, and it has the the output label wrong.
i also tried to change all label in the `.gds` and `.spice` to uppercase, and i event tried to change the pin-order of the `.spice` to the order of the `TOP_extracted.cir` from the LVS-script, but it didnt change anything...

**Comment by olisnr** [comment]
it seems there was a problem with the spice netlist. now it looks better i have no idea at the moment, why.
