### ISSUE TITLE
missing NW.d1 in Figure 5.1 of "SG13G2 Layout Rules Rev. 0.3"

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#199]
in `Figure 5.1` of `SG13G2 Layout Rules Rev. 0.3` i dont find the NW.d1Min. _NWell space to external N+Activ inside ThickGateOx0.62_

**Comment by sergeiandreyev** [comment]
@olisnr, most of the `<layer>.[a-z][0-9]` (like NW.e**1**) rules are not shown on the graphical figures in order not to overload the figures. The `d1`, `e1`, etc. rules for NWell describe the same rule but within ThickGateOx regions.

**Comment by KrzysztofHerman** [comment]
@olisnr  do you think that we can close this issue  ?
