### ISSUE TITLE
Invers operation correct?

### ISSUE THREAD

**Issue by dwarning** [IHP-GmbH/IHP-Open-PDK#2]
Hello,
I made few check with the vbic's in ngspice. Most things are plausible, but invers operation seems a bit strange. That's said without knowledge of the npn13G2 structure/crossview.
Can you comment the attached picture made with Vce=-1V and Vbc=0.3 ... 1V.
Thank you for the Open-PDK activity.
![Bildschirmfoto vom 2023-04-04 15-25-45](https://user-images.githubusercontent.com/18441932/229808642-06804f8b-4c44-49fd-a5dd-ae5b01fa2b02.png)

**Comment by bero4sc** [comment]
It is a HBT device. Why did you reverse bias the collector to emitter?

**Comment by dwarning** [comment]
Ok, answer by myself. Model seems plausible, if I see the lower Early voltage in reverse operation compared to forward.
BTW - at the moment the vbic temp control is buggy in ngspice - will be repaired in next release.
![Bildschirmfoto vom 2023-04-08 16-37-50](https://user-images.githubusercontent.com/18441932/230727279-5c92b78a-2850-4b4f-9506-e7f684cae238.png)
