### ISSUE TITLE
Xschem example circuits should not contain `pre_osdi`

### ISSUE THREAD

**Issue by hpretl** [IHP-GmbH/IHP-Open-PDK#20]
In situations where the VerilogA models are located in a central location (not in various simulation directories, but e.g. in `.../ngspice/lib/ngspice`) the `pre_osdi` directive leads to an error when starting `ngspice`.

As a consequence, this directive should not be part of the "standard" examples. Alternatively, it should be wrapped into a check whether this file exists in this local directory.

**Comment by olisnr** [comment]
i think the `pre_osdi ./psp103_nqs.osdi` belongs to the

`https://gitlab.com/dmt-development/ihp_sg13g2_compact_models`

**Comment by hpretl** [comment]
Yes, the statement `pre_osdi` loads the external PSP model into ngspice which is needed for the IHP MOSFET. But this model can be loaded from a central location with a central ngspice setting. Thus, the `pre_osdi` is not needed in every schematic.

**Comment by olisnr** [comment]
You would prefer `./simulation/.spiceinit` then?

**Comment by hpretl** [comment]
Not really. In our Docker image we just copy `psp103.osdi` into `.../ngspice/lib/ngspice`, and uncomment the corresponding line in `.../ngspice/share/ngspice/scripts/spinit`:

```
* Load the OpenVAF/OSDI models
if $?osdi_enabled

 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/asmhemt.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/bjt504t.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/BSIMBULK107.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/BSIMCMG.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/HICUMl0-2.0.osdi
 osdi /foss/tools/ngspice/ngspice/lib/ngspice/psp103.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/r2_cmc.osdi
 * osdi /foss/tools/ngspice/ngspice/lib/ngspice/vbic_4T_et_cf.osdi

end
```

This `spinit` is the default init `ngspice` reads.

**Comment by hpretl** [comment]
Since quite a few `.osdi` files are already there, and are included in the same way, it feels natural to add the PSP model there as well.

**Comment by hpretl** [comment]
It looks like this will be resolved soon: https://github.com/IHP-GmbH/IHP-Open-PDK/pull/162
