### ISSUE TITLE
DRC seem to miss error on GatPoly Gat.b or Gat.b1

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#201]
KLayout 2.9.6

2 different GatPoly should have 180nm or 250nm distance. but there is no DRC error at 70nm.

im not sure what the correct minimum is in this case:

![poly 70nm](https://github.com/user-attachments/assets/6c70f610-3aad-425b-b74e-c0f9df1b79bb)

**Comment by akrinke** [comment]
Thank you for the report! I have created the pull request #204 that should fix your problem. It updates the DRC script files [`sg13g2_maximal.lydrc`](https://raw.githubusercontent.com/IHP-GmbH/IHP-Open-PDK/bb559e2a6d23c66e1788eace1e6033d16964bf05/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc) and [`sg13g2_minimal.lydrc`](https://github.com/IHP-GmbH/IHP-Open-PDK/blob/bb559e2a6d23c66e1788eace1e6033d16964bf05/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc), so you just have to replace these files.

**Comment by olisnr** [comment]
@akrinke the minimal file gives me an error:
```
ich@P43s:~$ KLAYOUT_HOME='/home/ich/share/pdk/ihp-sg13g2/libs.tech/klayout'   klayout -e
ERROR: Reading /ALL/Xschem/ihp/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc: XML parser error: Root element must be klayout-macro in line 13, column 3
ERROR: Reading /ALL/Xschem/ihp/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc: XML parser error: Root element must be klayout-macro in line 13, column 3
```

**Comment by akrinke** [comment]
This is strange. The pull request has been merged just recently into the dev branch. The XML header has not been changed. Did you use the latest dev branch?

**Comment by olisnr** [comment]
i only replaced the two files. now i try `git clone -b dev --recursive https://github.com/IHP-GmbH/IHP-Open-PDK.git`

**Comment by olisnr** [comment]
now its working. 
i would also like an %-free DRC script that ignore all this % fill specifications. because routing-errors would be easier to eliminate, if one wouldnt need to go to check every time 10 filling errors, that show up anyway.

**Comment by sergeiandreyev** [comment]
> and are You interested to apply the commercial DRC and LVS tests with a little OTA, that seems to pass the openPDK DRC and LVS?

@olisnr, yes, we can run it

**Comment by sergeiandreyev** [comment]
> i would also like an %-free DRC script that ignore all this % fill specifications. because routing-errors would be easier to eliminate, if one wouldnt need to check every time 10 filling errors, that show up anyway.

it will be nice to have different DRC modes under switches (like it's done in OpenPDK LVS), that the user can easily setup from the GUI / cmdline based on what he needs

**Comment by olisnr** [comment]
@sergeiandreyev super thanks!

[OTA33.zip](https://github.com/user-attachments/files/17043983/OTA33.zip)

**Comment by akrinke** [comment]
I will look into switching DRC modes from the GUI. It should already be possible on the command line:
```
$ klayout -zz -s layout.gds -rd density=false -r sg13g2_minimal.lydrc
```

**Comment by sergeiandreyev** [comment]
> @sergeiandreyev super thanks!
> 
> [OTA33.zip](https://github.com/user-attachments/files/17043983/OTA33.zip)

ok, here comes the DRC part..
I have 16 DRC violations in this design:
- Cnt_d: 3
- M1_b: 2
- M1_e: 7
- M2_e: 1
- NW_b: 1
- NW_e: 2

_I'm not sure if I can share more w/o NDA_

**Comment by olisnr** [comment]
thanks a lot. 
i think, a print-screens of the error-markers should be ok, or a list of problematic coordinates. the errors are no secret, because the rules are public anyway.

**Comment by olisnr** [comment]
and one <180nm metal 1:

![Screenshot from 2024-09-19 21-58-15](https://github.com/user-attachments/assets/7ebe08a4-c328-47c6-87b5-78e748213ef8)

**Comment by olisnr** [comment]
metal 1 line > 300nm for >1µm distance > 220nm

![Screenshot from 2024-09-19 22-05-09](https://github.com/user-attachments/assets/90d8f938-1c54-4c62-87e4-efe5f217d073)

**Comment by olisnr** [comment]
Min. space of Metal(n) lines if, at least one line is wider than
0.39 µm and the parallel run is more than 1.0 µm:

![Screenshot from 2024-09-19 22-30-39](https://github.com/user-attachments/assets/702d14dd-4c75-4c9d-8145-bb74571d73ad)

**Comment by olisnr** [comment]
not really sure if i got this rule correct, but i think:

Min. NWell enclosure of NWell tie surrounded entirely by NWell in
N+Activ not inside ThickGateOx  0.24

is:

![Screenshot from 2024-09-19 22-47-25](https://github.com/user-attachments/assets/fb4b7dde-c54a-4b44-b140-99401734bd09)

**Comment by sergeiandreyev** [comment]
> the Cnt_d: 3 < 70nm i found already. the openPDK script was missing it:

all these violated rules (apart from `M1_e`) are not yet implemented ([link](
https://github.com/IHP-GmbH/IHP-Open-PDK/blob/dev/ihp-sg13g2/libs.tech/klayout/tech/drc/MissingRules_maximal.md))
@akrinke, do you have a preliminary timeline for the next bunch of DRC rules?

**Comment by sergeiandreyev** [comment]
please find attached the DRC violations coordinates:
[drc_OTA.txt](https://github.com/user-attachments/files/17075020/drc_OTA.txt)
how to read:
`8634 -46580` -> `8.634, -46.58`

**Comment by sergeiandreyev** [comment]
on the LVS:
- there are absent properties in CDL (`c` for `cmim`)
- discrepancies in `ng` for high-voltage PMOS devices

**Comment by akrinke** [comment]
> @akrinke, do you have a preliminary timeline for the next bunch of DRC rules?

We hope to deliver the next version in about two weeks.

**Comment by sergeiandreyev** [comment]
> and one <180nm metal 1:
> 
> ![Screenshot from 2024-09-19 21-58-15](https://private-user-images.githubusercontent.com/120017377/369150878-7ebe08a4-c328-47c6-87b5-78e748213ef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODg5NTMsIm5iZiI6MTcyNzA4ODY1MywicGF0aCI6Ii8xMjAwMTczNzcvMzY5MTUwODc4LTdlYmUwOGE0LWMzMjgtNDdjNi04N2I1LTc4ZTc0ODIxM2VmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMDUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ3Mzg2MjhjM2QwYTMxYzYzNTViOTU3N2JiMzVmMjkwMGVmZDdlZmYwMDFiOWU5YmZlZjE0NDhhMmJkOTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x06xjtMkQM_xb9PVk2CajxGSE7UscgVsEoA_1_MJfVs)

yes, this one is `M1.b`

**Comment by olisnr** [comment]
@sergeiandreyev can You run this also on DRC? i tried to fix all DRC errors. and then i have the question if its possible, to run the commercial DRC on layouteditor.de? or on microwaveOffice?
thanks a lot

[OTA_33u 51.gds.zip](https://github.com/user-attachments/files/17097343/OTA_33u.51.gds.zip)

**Comment by sergeiandreyev** [comment]
@olisnr, clean! 👍 
> if its possible, to run the commercial DRC on layouteditor.de? or on microwaveOffice?
I guess no, but let me double check..
can you post this question on Slack?

**Comment by sergeiandreyev** [comment]
Hi @olisnr, do you have any more questions, or we can close the ticket?

**Comment by olisnr** [comment]
sorry
