### ISSUE TITLE
.spiceinit seems to produce errors in AC simulation

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#205]
the `option savecurrents` from `ihp-sg13g2/libs.tech/ngspice/.spiceinit` produces an error in the ngspice-42 AC-simulation:
`Error: r.x7.r14: Current and power not available for ac analysis`

**Comment by holvo** [comment]
Please provide a simple test case showing this issue.

**Comment by holvo** [comment]
No test case required. A simple netlist like
```
test ac
.options savecurrents
V1 1 0 dc 0 ac 1
R1 1 2 1k
C1 2 0 1u
.control
ac dec 10 10 10k
display
plot mag(v(2)) mag(@r1[i])
.endc
.end
```
does show this error message. AC simulation and .options savecurrents are incompatible. A resulting vector like @r1[i] is not a complex number and thus does not show magnitude and phase, as is expected by ac results.

**Comment by KrzysztofHerman** [comment]
Solved in #217 PR

**Comment by sergeiandreyev** [comment]
Hi @olisnr, could you please provide your feedback if the solution works for you and you don't have any additional comments on this issue, after that we can close it

**Comment by olisnr** [comment]
looks good. thanks
