### ISSUE TITLE
Simulation of MOSFET noise with ngspice

### ISSUE THREAD

**Issue by 0y8w1x** [IHP-GmbH/IHP-Open-PDK#207]
## Environment

- Klayout Version: not applicable
- OS/Platform: Ubuntu 22.04

## Actual Behavior

I tried to do a noise simulation of a single common source transistor, but found the noise to be 0. In case the schematic is incorrect or I use the noise analysis wrong, please let me know. A simple DC analysis works just fine, so the general setup should be working.

My circuit looks like this:
![Screenshot from 2024-09-22 20-55-08](https://github.com/user-attachments/assets/b9aa9178-5cf6-4f83-af54-fdc62d174bc7)

And when I plot the onoise_spectrum/inoise_spectrum aswell as the total integrated noise I get the following:
![Screenshot from 2024-09-22 20-56-23](https://github.com/user-attachments/assets/79ee0a7c-a8cd-4089-a329-6ce1671c6d9c)

**Comment by bmurmann** [comment]
You are measuring the output noise at a node that is pinned to 1V, so I am not surprised that the result is zero. What are you trying to do?

**Comment by 0y8w1x** [comment]
> You are measuring the output noise at a node that is pinned to 1V, so I am not surprised that the result is zero. What are you trying to do?

Oh yeah that was a stupid mistake. I want to measure the intrinsic noise of the MOSFET

**Comment by KrzysztofHerman** [comment]
@0y8w1x could you please provide a correct testbench with some results. After that we could close the issue with a working example.

**Comment by dwarning** [comment]
Maybe these qucs-s/ngspice (NGSPICE_OSDI_DIR env variable have to be set) examples can help to close the issue:
![Bildschirmfoto vom 2024-10-09 17-43-31](https://github.com/user-attachments/assets/01136571-f2a6-470d-b8cb-f80a1ed1ee40)
![Bildschirmfoto vom 2024-10-09 17-44-03](https://github.com/user-attachments/assets/a6fa1cae-a35c-4a8f-b202-c6810ed51a38)

[lv_nmos_NOISE_id.sch.txt](https://github.com/user-attachments/files/17311124/lv_nmos_NOISE_id.sch.txt)
[lv_nmos_NOISE_vd_vg.sch.txt](https://github.com/user-attachments/files/17311125/lv_nmos_NOISE_vd_vg.sch.txt)

**Comment by KrzysztofHerman** [comment]
@dwarning we provide a sample `.spiceinit`, which sets the location of the OSDI file so you do not have to reference it on the schematic. The only thing you have to do is to create a symbolic link to this file under your `$HOME` direcory. I will also add some more controls to setup the noise plot type.

**Comment by dwarning** [comment]
Sorry, it was not the emphasis of my post. Anyway - thanks for hint.
What about induced gate noise. There are data and test benches available?

**Comment by 0y8w1x** [comment]
thanks @dwarning for the example, I reproduced it and it works great.
![Screenshot from 2024-10-12 17-44-16](https://github.com/user-attachments/assets/94fb0d43-17c4-442c-aea8-38f69bc5ee8c)

**Comment by dwarning** [comment]
Another test case in a 50 Ohm environment NF, NFMIN and Rgn =f(Freq)
![Bildschirmfoto vom 2024-10-14 13-56-15](https://github.com/user-attachments/assets/1a18a7df-3b76-4c03-9b9f-80a20c93c470)

**Comment by sergeiandreyev** [comment]
Hi @0y8w1x, do you have additional questions, or we can close the issue?

**Comment by 0y8w1x** [comment]
> Hi @0y8w1x, do you have additional questions, or we can close the issue?

can be closed, thank you.
