### ISSUE TITLE
[bug] Unexpected USE ANALOG

### ISSUE THREAD

**Issue by gudeh** [IHP-GmbH/IHP-Open-PDK#218]
Hi everyone. I believe I found an error on the PDK. 

Shouldn't the instances types `sg13g2_or2_1`, `sg13g2_or2_2` and `sg13g2_nand2b_1` have `USE SIGNAL` instead of `USE ANALOG` for their pins? As in [this part of the LEF](https://github.com/IHP-GmbH/IHP-Open-PDK/blob/5a42d03194e8c98558f4e34538338a60550f89b9/ihp-sg13g2/libs.ref/sg13g2_stdcell/lef/sg13g2_stdcell.lef#L4527).

**Comment by sergeiandreyev** [comment]
Hi @gudeh, could you please review if the updates are as expected and we can close the issue?
