### ISSUE TITLE
KLAYOUT Unable to open SG13G2 Technology Files and Pycell Library

### ISSUE THREAD

**Issue by Ikram-rs22** [IHP-GmbH/IHP-Open-PDK#219]
## Environment

- Klayout Version: 0.29.0
- OS/Platform: ubuntu 22

## Expected Behavior

KLayout should load the pycells of the SG13G2 PDK 

## Actual Behavior
We're trying to integrate the PDK with Klayout but after adding the technology files the following error occurs. 
![fzerror](https://github.com/user-attachments/assets/24abd58b-a90a-43c7-a0d4-d24f2a1d82b0)

As a result no nmos or npn library is present. Even if I specify the path of sg13g2_pycell_lib folder in the autorun.lym , it shows the following error
![giterror](https://github.com/user-attachments/assets/f6298106-8ded-40e5-bf9d-793990fbfaef)

Can anyone please guide me step by step on the integration process please? I know I'm asking for  a lot but I'm really struggling considering the fact I'm a beginner

## Steps to Reproduce the Problem

1. Klayout opening
2. Adding technology file .lyt from IHP PDK Path using Manage Technology package. Also adding sg13g2.lyp layer files
3.Restarting KLayout

**Comment by KrzysztofHerman** [comment]
@Ikram-rs22 thanks for reporting the issue. 
Let me guide you 

1. Clone the repository using `git clone --recursive https://github.com/IHP-GmbH/IHP-Open-PDK.git`
2. Setup PDK_ROOT, PDK, KLAYOUT_PATH and KLAYOUT_HOME in your `.bashrc`  file
```
export PDK_ROOT= your_directory/IHP-Open-PDK
export PDK=ihp-sg13g2 
export KLAYOUT_PATH="/home/$USER/.klayout:$PDK_ROOT/$PDK/libs.tech/klayout"
export KLAYOUT_HOME=/home/$USER/.klayout 
```
`source ~/.bashrc`

3.  Change the branch to `dev` 

```
cd $PDK_ROOT
git checkout dev
```
4.  Run klayout: `klayout -e`

**Comment by Ikram-rs22** [comment]
Thanks a lot Mr. Herman

**Comment by KrzysztofHerman** [comment]
@Ikram-rs22 Did it work for you ? Can we close the issue ?

**Comment by Ikram-rs22** [comment]
Yes thank you. Please kindly close this issue
