### ISSUE TITLE
Xschem S-parameter simulation problem

### ISSUE THREAD

**Issue by joerdsonsilva** [IHP-GmbH/IHP-Open-PDK#236]
Hello everyone. The S-parameter tests in the Xschem home page examples are not working correctly.

I'm using:
OS/Platform: linux
XSchem 3.4.5
NGSpice 43

**Comment by dwarning** [comment]
Can you give a link to the page with Xschem schematic.
What do you mean with "not working correctly"?

**Comment by KrzysztofHerman** [comment]
@joerdsonsilva I suppose you use the default examples provided in the PDK. As @dwarning said please provide tour testcase and your output that we could evaluate if there are issues or not.

**Comment by joerdsonsilva** [comment]
The problem has been solved. The error only appears when the option klu line in .spiceinit is not commented out. But when commenting out the option klu line, the S-parameter simulations work correctly in Xschem.
