### ISSUE TITLE
decap cells should be marked "CORE SPACER" in lef

### ISSUE THREAD

**Issue by gadfort** [IHP-GmbH/IHP-Open-PDK#237]
## Environment
OpenROAD uses this flag to determine if a cell can be removed during `remove_fillers`, without this the decaps cannot be removed for antenna fixes.

## Expected Behavior
decaps marked as SPACER to allow them to properly interact with the tools

## Actual Behavior
decaps are just marked CORE.

**Comment by b10346** [comment]
Ok, need to be investigated

**Comment by sergeiandreyev** [comment]
Hi @gadfort, could you please confirm that the update is as expected on your side as well.

**Comment by gadfort** [comment]
@sergeiandreyev yes, this works. Thank you.
