### ISSUE TITLE
Simulation problem with diode model and elevated temperatures

### ISSUE THREAD

**Issue by stafverhaegen-chipflow** [IHP-GmbH/IHP-Open-PDK#24]
I have a test case of an IO cell I am working on: [hightemp_sim.zip](https://github.com/IHP-GmbH/IHP-Open-PDK/files/13476981/hightemp_sim.zip)
You can run the simulations with the `./sim.sh` and that generates the included `sim25c.out` and `sim70c.out` files. As you can see the simulation works for 25℃ but not for 70℃. For 70℃ the reporter error is:
```
doAnalyses: TRAN:  Timestep too small; initial timepoint: trouble with darea-instance d.xtop.xnclamp.xdgate.d1
```

**Comment by KrzysztofHerman** [comment]
I have consulted this unusual behavior of the simulation with the developer of ngspice prof. Holger Vogt. He noticed that the model of the permi diode, which conforms the dantenna diode has an unusually low value of $v_j$ parameter, what causes convergence issues. The parameter itself varies with the temperature, what explain the situation that at $T=25$ the simulation converges and at $T=70$ does not. We will update the model as soon as we derive a valid value.

**Comment by sergeiandreyev** [comment]
we see the warnings in commercial simulator as well, but the default behavior we have there is that the `vj` parameter value is constrained to a larger value, this is why the simulation is not failing for internal PDK

**Comment by sergeiandreyev** [comment]
diode model `dperim` was fixed

**Comment by sergeiandreyev** [comment]
Hi @stafverhaegen-chipflow , could you please confirm that the issue is resolved and can be closed. 
Thanks,
 Sergei

**Comment by stafverhaegen-chipflow** [comment]
I can confirm that the simulations now run at elevated temperature.
Sorry for the delay.
