### ISSUE TITLE
Pcell "npn13G2_base" Layout Problem

### ISSUE THREAD

**Issue by rupokdas147** [IHP-GmbH/IHP-Open-PDK#242]
## Environment
Klayout
npn13G2_base

## Expected Behavior
![image](https://github.com/user-attachments/assets/6e6b4e63-32ed-4f82-b5e4-d6462f0cc299)

This image is downloaded from web.

## Actual Behavior
![image](https://github.com/user-attachments/assets/10e5e0cc-c46c-4915-a5b1-4d16d752f485)

This is the actual image in my Kalyout.

## Steps to Reproduce the Problem

1. Open klayout
2. Create new layout
3. Drag and drop "npn13G2_base" cell from the "SG13_dev - IHP SG13G2 Pcells" library.

**Comment by sergeiandreyev** [comment]
Hi @rupokdas147, the `npn13G2_base` could not be used by it's own - it's an internal part of the `npn13G2` device.
You should do these steps to instantiate this HBT device correctly:
- add `npn13G2_base` in layout
- add `npn13G2`, it should look like this:
![image](https://github.com/user-attachments/assets/def5d0a4-8d08-4767-b365-a2f6f392bf48)
- remove `npn13G2_base`

**Comment by sergeiandreyev** [comment]
I agree that this is not a very straightforward and user-friendly approach, we have to optimize it
