### ISSUE TITLE
Misbehavior of BJTs npn13G2/npn13G2l/npn13G2v

### ISSUE THREAD

**Issue by EngGhaith** [IHP-GmbH/IHP-Open-PDK#262]
Dear developers,
Dear community,

We have detected a kind of mistaken cross-talk between BJTs. You can find the whole description under this ngspice-forum issue on sourceforge:
https://sourceforge.net/p/ngspice/bugs/715/

Thank you in advance.
Best Wishes.
AL SABAGH Ghaith from IIC-JKU.

**Comment by KrzysztofHerman** [comment]
Dear @EngGhaith thank you for providing your feedback

although this cross-talk we have not  observed yet we had some issues with the terminals of the devices, which were affecting ie. hierarchical design in xschem.  There is a PR https://github.com/IHP-GmbH/IHP-Open-PDK/pull/261 on our github which introduces changes in the HBT devices subcircuits and provides two variants of each HBT like shown below:

Device | 4 terminal subcircuit name | 5 terminal subcircuit name
---------- | ---------- | ------ 
npn13G2      | npn13G2       | npn13G2_5t 
npn13G2l     | npn13G2l       | npn13G2l_5t 
npn13G2v      | npn13G2v       | npn13G2v_5t 

The changes were introduces in `sg13g2_hbt_mod.lib` file

If you reproduce the testcase using our update we would appreciate the results

**Comment by EngGhaith** [comment]
[PA12BugReport_3.zip](https://github.com/user-attachments/files/17750549/PA12BugReport_3.zip)

I have tried the 4 terminal device and it shows the same behavior as before.
The 5 trminal device throws me subkt error.
But I am not sure if I checked out to the PR rightly. :)

Therefore I have uploaded the Xschem-Schematic-File in the zipped file. Could you please test it again to confirm the misbehavior?

Steps for 4-terminal device:
1- Simulate for first time within V3=0V8
2- See the results of .meas statement
3- Change V3 to V3=0V85
4- Resimulate 
5- You will see that the current of the Transistor XQ1 has been changed, although you havent change its bias (VCC1 or VBB1)

And may you can check, if the 5-terminal device is really faulty.

Thank you very much.
AL SABAGH Ghaith from IIC-JKU.

**Comment by KrzysztofHerman** [comment]
Dear @EngGhaith 

I have just reproduced your testcase and got no cross-talks. In booth cases the value of `ic1` current is the same and does not depend on `V3` source value. 

```
ic1                 =  3.255779e-04
ic2                 =  1.323070e-03

```

In order to checkout the PR of a given number PR like #261 go to the `$PDK_ROOT` and execute the following:

In a case you have cloned your own fork:
```
git fetch upstream pull/261/head 
git checkout FETCH_HEAD
```
In a case you have just cloned our repository
```
git fetch origin pull/261/head 
git checkout FETCH_HEAD
```
Good luck!

**Comment by EngGhaith** [comment]
Dear @KrzysztofHerman 
Thank you for your input.
I could bound the new symbols by manually copying subkts.
Now there is no interference between operation points at the steady-state.
I have used a test bench with .tran-simulation and observed the behaviour, that by stepping the base-voltage of XQ2/XQ4/XQ6 from 0V80 to 0V85 the current of XQ1/XQ3/XQ5 is mistakenly affected, but it will return to the its normal value at steady-stateafter the transition.
Could you please explain me this behavior?
Is it something normal or not?
What is the IHP-recommendation regarding how to tie thermal pin? should it be tied to GND? or what?
[PA12BugReport_PR261.zip](https://github.com/user-attachments/files/17802948/PA12BugReport_PR261.zip)

The testbench with screenshots are attached.
XQ1, XQ2 --> 4-terminal devices
XQ3, XQ4 --> 5-terminal devices with unconnected thermal pins. ==> they have same behavior as 4-terminal devices!
XQ5, XQ6 --> 5-terminal devices with GND-connected thermal pins.

**Comment by EngGhaith** [comment]
Dear developers
@KrzysztofHerman 
@sergeiandreyev 
I have simulated a similar example in Xyce and the results were very healthy.
The simulated netlist are listed below:

`VCC1 net1 0 1.8
VBB1 net3 0 0.80
VBB2 net7 0 PULSE(0.8 0.85 500n 10p 10p 500n 1u 1)
XQ1 net5 net6 0 0 t npn13G2l Nx=1 El=1
VCC2 net2 0 1.8
Vic2 net2 net4 0
Vic1 net1 net5 0
Vib1 net3 net6 0
Vib2 net7 net8 0
VCC3 net9 0 1.8
VBB3 net10 0 0.80
Vic3 net9 net12 0
Vib3 net10 net11 0
VCC4 net13 0 1.8
Vic4 net13 net16 0
Vib4 net14 net15 0
XQ2 net4 net8 0 0 t npn13G2l Nx=1 El=1
XQ3 net12 net11 0 0 27.0000001 npn13G2l Nx=1 El=1
XQ4 net16 net15 0 0 27.0 npn13G2l Nx=1 El=1
VBB4 net14 0 PULSE(0.8 0.85 500n 10p 10p 500n 1u 1)
**** begin user architecture code
.tran 5f 550n 450n
.print tran format=raw file=PA12BugReport_PR261_v2_XYCE_dlatest.raw v(*) i(*)
.lib /foss/pdks/sg13g2/libs.tech/xyce/models/cornerHBT.lib hbt_typ`

XQ1 and XQ2 are 4-terminal symbols.
XQ3 and XQ4 are 5-terminal symbols.
I have adapted ALL transistors manually in the netlist to let the simulation work.
I have tied XQ3 to 27.0000001 and XQ4 to 27.0 to simulate both devices at the temperature 27. This walkaround was necessary, because if I tie both to 27, then they will be thermally coupled and XQ3 will have a mistaken change in operation point whithin the changing the op of XQ4.
If you simulate the circuit, then you will see that XQ1 and XQ2 are behavioring mistakenly. That is because both of them is tied to the node 't'=temperature.
![XYCEBugReport1](https://github.com/user-attachments/assets/7029a18c-5299-44e7-82b4-dc756b8a5c25)
![XYCEBugReport2](https://github.com/user-attachments/assets/8a2f062a-5cff-479b-be84-1f5cc45a3702)
In the plots you can see all details, which I have explained. Red are XQ3,XQ4 and Green are XQ1,XQ2.
The plot in net7 is showing the step of base Voltage of XQ2/XQ4.
**The only strange thing in the results is that the base currents have negative sign.**

I think you can compare the results in Ngspice and Xyce to analyze the misbehavior in Ngspice-models as described before.

Please adapt the library-files for Xyce to allow direct simulation in Xschem with Xyce using 4t/5t-symbols without changing netlists manually.

Thank you in advance.
AL SABAGH Ghaith from IIC-JKU.

**Comment by KrzysztofHerman** [comment]
@EngGhaith thank you for the feedback. Yesterday I have pushed some changes in PR #283 where 5 terminal models for Xyce are introduced. You could check it and report how it perform.

**Comment by EngGhaith** [comment]
![XYCEBugReport3](https://github.com/user-attachments/assets/e4023554-b451-4834-b329-f3f331ef9587)
Dear developers
@KrzysztofHerman 
@sergeiandreyev 

Results are OK.
I have these warnings from XYCE:

_***** Reading and parsing netlist...
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 282
 No model parameter VBE_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 282
 No model parameter VBC_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 282
 No model parameter VCE_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 386
 No model parameter VBE_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 386
 No model parameter VBC_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
Netlist warning in file
 /foss/pdks/sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib at or near line 386
 No model parameter VCE_MAX found for model NPN13G2L_NX_VBIC of type NPN,
 parameter ignored.
***** Setting up topology..._

Some Remarks:
1. Why are base currents negative? wrong direction in model defined?
2. Could you please supply these models with warning messeges, when terminal voltage differences are exceeded (VBE is over 0V9, VCE is 0ver XV,...etc. as in Ng-Spice-Symbols in main branch) 

Thank you in advance.
AL SABAGH Ghaith from IIC-JKU.

**Comment by KrzysztofHerman** [comment]
@EngGhaith thank you for the feedback. We are considering adding warnings messages for our devices.

**Comment by KrzysztofHerman** [comment]
Is there something more or we close the issue  ?
