### ISSUE TITLE
is it possible to get measured data of the sg13g2_pr.gds pnpMPA?

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#27]
... to be able to fit a spice pnp-model to it. because it seems, that it will need long time until the real models are ready.

this would be very helpful.

**Comment by sergeiandreyev** [comment]
the measurement data for the `pnpMPA` device is uploaded to the repository, models will be coming soon.
please note that the w/l of the measured device could be slightly different in comparison w/ the layout in `sg13g2_pr.gds`

**Comment by olisnr** [comment]
great! thanks a lot!
