### ISSUE TITLE
adms-compile-va.sh script writes in a nonextisting directory: 

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#270]
## Environment
`git clone -b dev --recursive https://github.com/IHP-GmbH/IHP-Open-PDK.git
`
## Expected Behavior
`~/share/pdk/ihp-sg13g2/libs.tech/xyce/adms$ ./adms-compile-va.sh
`
should compile plugins into the plugin directory `buildxyceplugin psp103.va ../../plugins`

## Actual Behavior
but there is no directory from git clone, and no is created from in the script

## Steps to Reproduce the Problem
clone the dev-branch
run `./adms-compile-va.sh
`

maybe the script should be updated with `mkdir  ../../plugins`, or maybe i clone somehow wrong :)

**Comment by KrzysztofHerman** [comment]
@olisnr 
thank you for commenting on that. We have also detected this issue and it is already fixed [here](https://github.com/KrzysztofHerman/IHP-Open-PDK/blob/xschem-tests-dir/ihp-sg13g2/libs.tech/xyce/adms/adms-compile-va.sh) and soon will be integrated in the 'dev' branch.
