### ISSUE TITLE
[DRC] Violating M2.b is sometimes not detected

### ISSUE THREAD

**Issue by hpretl** [IHP-GmbH/IHP-Open-PDK#275]
We are currently working towards a tapeout, and had a situation where the DRC fail below has not been detected by the current KLayout DRC rules. `M2.b` is clearly violated.

<img width="982" alt="image" src="https://github.com/user-attachments/assets/0a2d49f4-4435-439a-acee-6bf460896581">

**Comment by hpretl** [comment]
@akrinke Can you please take a look?

**Comment by sergeiandreyev** [comment]
Hi @hpretl, I have it flagged by the `minimal` rule deck:
![image](https://github.com/user-attachments/assets/397e9425-8cdb-4ec7-9e6f-cb52bc8d1036)
Could you please attach your testcase?

**Comment by hpretl** [comment]
@sergeiandreyev Here is the M2 layer of the chip. Maybe we used an outdated DRC runset? Let's see if the error is flagged on your end.

[tc_m2_fail.oas.gz](https://github.com/user-attachments/files/17909010/tc_m2_fail.oas.gz)

**Comment by sergeiandreyev** [comment]
yep, it is found:
![image](https://github.com/user-attachments/assets/80673e3b-d2de-4716-a279-0e4e9cd8ec60)
I'm using latest deck from `dev` branch:
https://github.com/IHP-GmbH/IHP-Open-PDK/blob/dev/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc

**Comment by hpretl** [comment]
@sergeiandreyev Thanks for checking! We need to find out why we missed the fail. I propose to close this issue.
