### ISSUE TITLE
pnpMPA parameters cant be set or read

### ISSUE THREAD

**Issue by PhillipRambo** [IHP-GmbH/IHP-Open-PDK#288]
I am experiencing that the pnpMPA model, has to input parameters in terms of W and L. However it doesnt seem like these values mean anything. In the netlist not able to read the area, perimiter etc.. Looking at the model in the PDK it looks like its defined with the following parameters:

.param a=2p p=6u ac=13.33p pc=14.64u

For which W and L this is applicable for i dont know.

**Comment by sergeiandreyev** [comment]
Hi @PhillipRambo, could you please double check from your side that with the latest update the area and perimeter are available in the extracted netlist

**Comment by KrzysztofHerman** [comment]
Close as solved
