### ISSUE TITLE
Discrepancy in Bulk Substrate Thickness

### ISSUE THREAD

**Issue by Iranildot** [IHP-GmbH/IHP-Open-PDK#296]
## Context
I was writing a .tek file for ASITIC app and I found the bulk substrate thickness measurement with two different values. 

- SG13G2_os_process_spec.pdf: 750 um
- Using OpenEMS Python with IHP SG13G2 v1.1.pdf: 280 um

## Screenshots

![Captura de tela 2024-12-16 093454](https://github.com/user-attachments/assets/2682f59b-e512-4a18-85ab-b463313228d5)
![Captura de tela 2024-12-16 093406](https://github.com/user-attachments/assets/a3a570d4-079c-41ad-a367-ea50e9cce055)

## Question

Which value is the right value?

**Comment by KrzysztofHerman** [comment]
@Iranildot the valid answer is `280 um` and it should be used in your modeling. The `750 um` comes form the wafer processed in our clean room which is then mechanically postprocess to get different thicknesses.

**Comment by olisnr** [comment]
@Iranildot You write a tech file for ASiTiC?

**Comment by hpretl** [comment]
@sergeiandreyev Yes, I think that would be helpful.

**Comment by KrzysztofHerman** [comment]
More information about the options of the wafer thickness offered by IHP can be found [here](https://www.ihp-microelectronics.com/services/research-and-prototyping-service/mpw-prototyping-service/schedule-price-list)

**Comment by VolkerMuehlhaus** [comment]
One more comment: the 280 micron bulk silicon thickness results in 300 micron total thickness of the stackup. Thickness specified by IHP is total chip thickness.
