### ISSUE TITLE
missing model for `sg13_lv_nmos`

### ISSUE THREAD

**Issue by proppy** [IHP-GmbH/IHP-Open-PDK#3]
Trying to run the following ngspice simulation:
```
.title sg13g2_inv_1
.lib /content/IHP-Open-PDK/ihp-sg13g2/libs.tech/ngspice/models/SG13G2_hbt_woStatistics.hsp.lib
.include /content/IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_stdcell/spice/sg13g2_stdcell.spice

X1 GATE DRAIN VPWR 0 0 VGND sg13g2_inv_1

Vgnd  VGND  0     0
Vdd   VPWR  VGND  5.0
R     VPWR  DRAIN 50k
Vin   GATE  VGND  DC    0V
.op
.option post nomod
.end

.control
save all GATE DRAIN
dc Vin 0 5.0 0.01
display
wrdata output.txt GATE DRAIN
.endc
```
will result in the following error:
```
Error: unknown subckt: x1.xx1 vpwr gate 0 vpwr x1.sg13_lv_nmos x1.w=740.00n x1.l=130.00n x1.ng=1 x1.ad=0 x1.as=0 x1.pd=0 x1.ps=0 m=1
    Simulation interrupted due to error!
```

See the following notebook which reproduce the issue:
https://colab.research.google.com/gist/proppy/5582eeae8d2e2eccb48cd591b904185f/ihp-pdk-playground.ipynb

**Comment by proppy** [comment]
Is that expected? (i.e: the model for nmos/pmos will only get developed/released later)

**Comment by sergeiandreyev** [comment]
Hi! Yes, this is expected.. For now, we have only models for HBT (BJT) devices, for the MOSFET models we're still discussing the Spectre to SPICE format translation with 3rd parties. I hope they will be released in summer timeframe.
Also we're considering to put nmos/pmos Spectre models to the GitHub (but this will certainly help you only in case you have access to the simulator that supports them)

**Comment by proppy** [comment]
maybe @RTimothyEdwards and @atorkmabrains can share some insight on how the conversation was done respectively for SKY130 and GF180MCU.

**Comment by atorkmabrains** [comment]
@sergeiandreyev @proppy we actually use home grown scripts for this. But we also go into debugging the model card parameters and tweak them to match the desired outcome. That's why we always request a golden measurements data that we could use as a reference. It's very lengthy process if we faced issues related to not matching behaviors. 

@sergeiandreyev Please contact me privately at linkedin if you want us to collaborate: https://www.linkedin.com/in/amro-t-24701458/

**Comment by atorkmabrains** [comment]
@sergeiandreyev You don't need to release spectre Model cards for that BTW.

**Comment by mithro** [comment]
https://semimod.de/ -- who is based in Europe might also be able to offer assistance, particularly if you are doing recharacterization stuff or regenerating from raw data.

The topic of spice model generation and validation comes up at lot in the CHIPS Alliance Analog work group (https://www.chipsalliance.org/workgroups/) and on the SKY130 raw data repository (https://github.com/google/skywater-pdk-sky130-raw-data).

**Comment by metroid120** [comment]
Markus from SemiMod: Thanks for your efforts @noherbrferurtth @proppy 
We are looking forward to helping with the model conversion and will join the IHP meeting that is coming up.

Also, I am delighted to share that we recently got funding for developing an open-source MOS Model extraction tool, so we are currently looking for (i) reference models and (ii) a test chip for measurement. 
I think the IHP technology would be perfectly suited.

**Comment by sergeiandreyev** [comment]
- we have now MOS Spectre models available in the repo: `libs.tech/spectre`
- and SemiMod @metroid120 did an outstanding job to convert these models for use w/ ngspice & Xyce (also HBT models were updated)
   The data is located in their GitLab repository https://gitlab.com/dmt-development/ihp_sg13g2_compact_models

**Comment by sergeiandreyev** [comment]
update: we now have device simulation models available in the repo: `lib.tech/ngspice/models`
for usage please consult respective readme files and documentation on SemiMod GitLab [repo](https://gitlab.com/dmt-development/ihp_sg13g2_compact_models)

**Comment by sergeiandreyev** [comment]
Hi @proppy , I guess this issue is resolved now.. Can we proceed and close this item as  fixed?

**Comment by KrzysztofHerman** [comment]
Mosfets models available in `libs.tech/ngspice/`
