### ISSUE TITLE
SOA checks for sg13g2 MOSFETs

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#30]
is it possible to do ngspice-simulations with SOA-checks? i didnt found anything about it in the documentation.

**Comment by KrzysztofHerman** [comment]
Yes it is possible. Take a look at chapter 11.5 in [ the ngspice manual](https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-23015). We are collecting the data to provide this kind of warnings in our PDK but this task it not a high priority one. Can we close this issue ?

**Comment by olisnr** [comment]
ok
