### ISSUE TITLE
documentation: IHP-Open-PDK-main/ihp-sg13g2/libs.tech/xschem/README.md could be enhanced

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#31]
the `m` in the MOSFETs isnt working yet (should be mentioned), and the non-transistor parameters arent  indicated generally. the resistor models as example have an `b` parameter, thats not described. could it be number of bends?

**Comment by sergeiandreyev** [comment]
this information will be provided as part of the process spec document for every device used in the PDK (unfortunately it's update is still in progress..)
regarding the resistor `b` parameter, you're correct:
> Number of bends. For large R values a meander shape is useful to generate a more compact device at the expense of accuracy. Integer number.

**Comment by olisnr** [comment]
thanks.
