### ISSUE TITLE
difference between npn13g2 and npn23g2l

### ISSUE THREAD

**Issue by hmohajeri** [IHP-GmbH/IHP-Open-PDK#39]
I'm reviewing page 20 of "SG13G2 Process Specification Rev. 1.1" and noticed that the tables for "npn13g2" and "npn13g2l" are very similar. Could anyone clarify the purpose of having "npn13g2l" listed separately? It seems like "npn13g2" might be able to replace it. Any insights on this would be appreciated.

Thanks!

**Comment by KrzysztofHerman** [comment]
@hmohajeri The npn13g2l has two variable parameters: Nx - number of emitters and El - emitter length. The feature of the variable emitter length is characteristics only for this device, npn13g2 and npn13g2v have fixed emitter length.
