### ISSUE TITLE
Wrong signal class for sg13g2_o21ai_1 cell

### ISSUE THREAD

**Issue by KrzysztofHerman** [IHP-GmbH/IHP-Open-PDK#4]
Trying to port the IHP Open PDK to the OpenRoad-flow-scripts I got some issues with detailed routing. The exact bug is the following `[ERROR DRT-0307] Net 000 of signal type SIGNAL cannot be connected to iterm 318/Y with signal type POWER Error: detail_route.tcl, 59 DRT-0307`  The instance 318 is a  `sg13g2_o21ai_1` cell and its output is assigned to `USE POWER;` signal class in the LEF file.

**Comment by sergeiandreyev** [comment]
stdcell LEF: `sg13g2_o21ai_1` pin Y signal class fixed (POWER->SIGNAL) as a temporary workaround, LEF should be regenerated

**Comment by KrzysztofHerman** [comment]
LEF view updated.
