### ISSUE TITLE
spef file resistor and capacitor value

### ISSUE THREAD

**Issue by hmohajeri** [IHP-GmbH/IHP-Open-PDK#41]
After routing an example design the results from *.spef file list all the node capacitor as zeros and the resistor either 40-ohm or 20-ohm.

**Comment by KrzysztofHerman** [comment]
@hmohajeri could you please share your testcase in order to reproduce the results?

**Comment by sergeiandreyev** [comment]
Hi @hmohajeri, could you please provide the testcase data to better follow up on this?

**Comment by hmohajeri** [comment]
Hi @sergeiandreyev this note was awhile back and don't have the test case any more. It was related to openRoad. I will send you a note if I get time to replicate it again.
