### ISSUE TITLE
clk-pin not reacheable

### ISSUE THREAD

**Issue by mi-and-core** [IHP-GmbH/IHP-Open-PDK#5]
In sg13g2_dfrbp_2 clk-pin (Metal1, red) is masked by reset_B (Metal2, blue) :

![clk_masked](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/54540406/90fd5e8e-2633-4c67-8f1a-aa1cfbd03dac)

**Comment by sergeiandreyev** [comment]
please take a look at the latest stdcell update, this should be fixed now
