### ISSUE TITLE
KLayout: PMOS and NMOS have different GatPoly Layers

### ISSUE THREAD

**Issue by vkrahul77** [IHP-GmbH/IHP-Open-PDK#54]
In the "IHP Pycells", For Gate The PMOS has "GatPloy.lbl" while NMOS has "Gatpoly.drw" as shown:
![GatePloy_PMOS_NMOS](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/156023726/f1d41ef9-a32f-4880-870a-77f601ac2c74)

Also, I've noticed a discrepancy in dimension input between NMOS and PMOS transistors within the tool. Specifically, while "1u" notation is accepted for PMOS, it's not permitted for NMOS. Instead, we're required to use scientific notation such as "1e-6".

**Comment by ihpopenpdk** [comment]
it seems to be an issue in both `nmos` and `pmos` cells - there should be no any '.lbl' or '.bnd' `GatPoly` layers, only '.drw' and '.pin'..
Thank you for finding!

**Comment by vkrahul77** [comment]
Along with the posted bug, I noticed that there are a few DRC errors in NMOS-Cell. 
Here is a list:
Min and Max size of contact should be 0.16  --> Cell has 0.14
Min Contact space should be 0.18 --> Cell has 0.16
Min Metal1 space or notch should be 0.18 --> Cell has 0.13
<img width="541" alt="image" src="https://github.com/IHP-GmbH/IHP-Open-PDK/assets/156023726/d1fce0ba-3129-48cd-9f21-950e95630a93">

**Comment by sergeiandreyev** [comment]
@vkrahul77 , I believe all these issues are fixed in the latest OpenPDK `dev` branch:
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/116548619/6613bbde-69aa-442d-b12d-db5ad1deafe4)

**Comment by vkrahul77** [comment]
Sure! Please go ahead and close the ticket.
Sincerely,
Vikas
