### ISSUE TITLE
DCO enforced without defined what signed-off-by: means

### ISSUE THREAD

**Issue by FatsieFS** [IHP-GmbH/IHP-Open-PDK#8]
DCO should only be enforced in CI if it is defined in README, contribution guide or other documentation what the actual signed-off-by means.

**Comment by sergeiandreyev** [comment]
Hi Staf, could you please check the README and the Contributing guidelines now pushed to the repo - if the information available there is enough from your point of view.
Thanks,
 Sergei

**Comment by FatsieFS** [comment]
Yes, perfect.
