### ISSUE TITLE
Incorrect pad recognition rule in Layout Rules Chapter 6.9

### ISSUE THREAD

**Issue by DanielGerlicher** [IHP-GmbH/IHP-Open-PDK#81]
""Device recognition: Pad = (Passiv + Passiv:sbump + Passiv:pillar) + dfpad""

Shouldn't this be

""Device recognition: Pad = (Passiv OR Passiv:sbump OR Passiv:pillar) + dfpad""

?

**Comment by KrzysztofHerman** [comment]
@DanielGerlicher thank you for the comment. Actually "+" is an equivalent of OR so, keeping this in mind, we will rather maintain the existing version.
