### ISSUE TITLE
nmos_code.py question

### ISSUE THREAD

**Issue by eskiyerli** [IHP-GmbH/IHP-Open-PDK#82]
Can you explain to me what does this piece of pycell code is doing? As far as I see, it is just redrawing the same box (rectangle) at the same location as many times as there are gate fingers:

        for i in range(int(ng)) :
            # draw the poly line
            xpoly_beg = xcont_end+gatpoly_cont_dist
            ypoly_beg = ydiff_beg-gatpoly_Activ_over
            xpoly_end = xpoly_beg+l
            ypoly_end = ydiff_end+gatpoly_Activ_over
            dbCreateRect(self, poly_layer, Box(xpoly_beg, ypoly_beg+diffoffset, xpoly_end, ypoly_end+diffoffset))

I am trying to port this pycell code to Revolution EDA, and I am a bit perplexed.

**Comment by sergeiandreyev** [comment]
Hi @eskiyerli,
 this `for` loop goes from lines 181 to 212, `xcont_end` and other variables that are used to define gate coordinates are getting recalculated inside.
You can check this by debug printing inside the loop.
Hope this will answer your question.
