### ISSUE TITLE
dantenna & dpantenna netlisting

### ISSUE THREAD

**Issue by bmurmann** [IHP-GmbH/IHP-Open-PDK#88]
The pin order of these diodes in spice netlists is alphabetical, and currently gives the pin order cathode, anode. This is incompatible with standard spice, where diodes are instantiated as anode, cathode.

This problem has trickled down into the LVS, which now expects the wrong cathode, anode order. The existing netlist for the IO cells uses the proper spice ordering and therefore does not pass LVS.

I strongly recommend going with the spice standard; anything else will be extremely confusing.

**Comment by FaragElsayed2** [comment]
Done in #93 

Cc @atorkmabrains

**Comment by sergeiandreyev** [comment]
@bmurmann, could you please confirm that with the latest LVS update the issue is fixed?

**Comment by bmurmann** [comment]
Confirmed, this is fixed.
