### ISSUE TITLE
LVS vs. resistor positioning

### ISSUE THREAD

**Issue by KrzysztofHerman** [IHP-GmbH/IHP-Open-PDK#91]
I found a weird behavior when doing a LVS test with resistors. The first case (left in the image) pass LVS with any problem when the last resistors is at the same level (red line), but if I move the last resistor just a little bit to the south (right in the image) then the LVS fails. Does anyone know why is this happening?

[Slack Message](https://open-source-silicon.slack.com/archives/C0549N94FD3/p1714483010992259)

**Comment by FaragElsayed2** [comment]
Done in #93 

Cc @KrzysztofHerman @atorkmabrains

**Comment by KrzysztofHerman** [comment]
Confirmed and closed.
