### ISSUE TITLE
Option GUI (alpha LVS)

### ISSUE THREAD

**Issue by bmurmann** [IHP-GmbH/IHP-Open-PDK#98]
I am having some trouble getting the options from the GUI to be correctly reflected in the LVS run. I see that the yml file gets updated when I click an option, but when I click "load pdk options" the sync between the menu buttons and the yml is lost until all options are manually toggled into alignment again. 

Furthermore, when I start KLayout, the yml file has schematic_simplify: true, but the GUI menu has Netlist simplify enabled (and not netlist simplify).

Why is there a "tile" run option for LVS? 

Also, just a suggestion for the documentation of the options, I found this to be a useful explanation from the KLayout manual:
Netlist simplify is a wrapper for "make_top_level_pins", "purge", "combine_devices" and "purge_nets" in this recommended order.

**Comment by sergeiandreyev** [comment]
@bmurmann, could you please confirm that with the latest LVS update the issue is fixed?

**Comment by bmurmann** [comment]
Confirmed, this is fixed.
